import Head from "next/head";
import {useRouter} from "next/router";
import {useEffect, useState} from "react";
import CardVoos from "@/components/cards/CardVoos";
import {getDataVoos} from "@/pages/api/getDataVoos";
import {format} from "date-fns";

function Voos() {
    const router = useRouter();
    const [voos, setVoos] = useState([]);

    const {origem, destino, data_partida} = router.query;

    console.log(origem, destino, data_partida)

    useEffect(() => {
        const getData = async () => {
            try {

                const voosDados = await getDataVoos();

                console.log(voosDados)

                const voosFiltrados = voosDados.filter((voo) => {

                    const formattedInputDate = format(new Date(data_partida), 'yyyy-MM-dd');
                    const formattedVooDate = format(new Date(voo.data_partida), 'yyyy-MM-dd');

                    return (
                        (voo.cidadeSaida).toLowerCase().includes(origem.toLowerCase()) &&
                        (voo.cidadeChegada).toLowerCase().includes(destino.toLowerCase()) &&
                        formattedVooDate === formattedInputDate
                    );
                });

                console.log("Voos Filtrados", voosFiltrados)
                setVoos(voosFiltrados);
            } catch (error) {
                console.error("Erro ao buscar dados", error);
            }
        };

        getData();
    }, [origem, destino, data_partida]);


    console.log(voos)

    return (
        <>
            <Head>
                <title>Agencia de Viagems - Voos </title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className="container mt-5">
                {voos && voos.length > 0 ? (
                    voos.map(vooMap =>
                        <div key={vooMap.id}>
                            <CardVoos voo={vooMap}/>
                        </div>
                    )
                ) : (
                    <>
                        <p className="text-danger fw-bold">Ops.. Nao encontramos nenhum voo no momento, tente novamente
                            com outra data!</p>
                        <button className="btn btn-danger" onClick={(event) => {
                            event.preventDefault()
                            router.push('/')
                        }}>Buscar novamente
                            <img width="20" className="ms-2" height="20"
                                 src="https://img.icons8.com/ios/50/search--v1.png" alt="search--v1"/>
                        </button>
                    </>
                )}
            </main>
        </>
    );
}

export default Voos;
