import Head from "next/head";
import React, {useEffect, useState} from "react";
import {useRouter} from "next/router";
import {useAuth} from "@/context/authContext";
import {useForm} from "react-hook-form";
import {http} from "@/utils/http";
import data from "bootstrap/js/src/dom/data";
import axios from "axios";
import ButtonFechar from "@/components/ButtonFechar";
import ModalComponent from "@/components/ModalComponent";
import {getTokenVerify} from "@/pages/api/getTokenVerify";

const UpdateEmpresaAerea = ()=>{

    getTokenVerify();

    const {token} = useAuth();
    const router = useRouter();

    const [modalIsOpen, setModalIsOpen] = useState(false);

    const openModal = () => {
        setModalIsOpen(true);
    };

    const closeModal = () => {
        setModalIsOpen(false);
        router.push('/backoffice/companhia_aerea')
    };

    const {codigo} = router.query;
    const [status, setStatus] = useState(false);
    const [error, setError] = useState(false);

    const {
        register,
        handleSubmit,
        formState: {errors},
        setValue
    } = useForm();

    useEffect(() => {
        if (codigo){
            http.get(`/empresasaereas/${codigo}`,{
                headers:{
                    'Authorization': `Bearer ${token}`
                }
            })
                .then((response)=>{
                    Object.keys(response.data).forEach((key)=>{
                        setValue(key, response.data[key])
                    })
                })
        }
    }, [codigo, token, setValue]);

    const onSubmit = async (data) =>{
        try {
            await  http.put(`/empresasaereas/${codigo}`, data,{
                headers:{
                    'Authorization': `Bearer ${token}`
                }
            })
                .then(response =>{
                    setStatus(true)
                    openModal()
                })
        }catch (error) {
            if (axios.isAxiosError(error) && error.response) {
                console.error('Erro na resposta da API:', error.response.data);
                setError(true)
            } else {
                console.error('Erro ao enviar dados para a API:', error);
                setError(true)
            }
        }
    }

    return(
        <>
            <Head>
                <title>Agencia de Viagems - Editando Empresa </title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className="container mt-5">
                <form className="form-control p-5">
                    <ButtonFechar url="/backoffice/aeroporto"/>
                    <input className="form-control mb-3 mt-3"
                           placeholder="Nome"
                           id="nome"
                           {...register("nome", {required: true})}
                    />
                    {errors?.nome?.type === "required" && (
                        <p className="text-danger fw-bold">Campo Obrigatorio</p>
                    )}
                    <input className="form-control mb-3"
                           placeholder="CNPJ"
                           id="cnpj"
                           {...register("cnpj", {required: true})}
                    />
                    {errors?.codigo?.type === "required" && (
                        <p className="text-danger fw-bold">Campo Obrigatorio</p>
                    )}

                    <div>
                        <button className="btn btn-success  pe-5 ps-5"
                                onClick={(e) => {
                                    e.preventDefault();
                                    handleSubmit(onSubmit)()
                                }}
                        >Salvar
                        </button>
                    </div>


                    {status === true ? (
                        <ModalComponent isOpen={openModal}>
                            <p>Empresa alterada com sucesso</p>
                            <div className="d-flex justify-content-end">
                                <button className="btn btn-success" onClick={closeModal}>OK</button>
                            </div>

                        </ModalComponent>
                    ) : (
                        ""
                    )}

                    {error === true?(
                        <p className="text-danger fw-bold mt-4">Erro ao salvar, verifique os dados e tente novamente!</p>
                    ):("")}

                </form>
            </main>
        </>
    )
}

export default UpdateEmpresaAerea;