import React, {useEffect, useState} from 'react';
import Head from "next/head";
import {useAuth} from "@/context/authContext";
import {useRouter} from "next/router";
import {http} from "@/utils/http";
import Link from "next/link";
import Paginacao from "@/components/Paginacao";
import ModalComponent from "@/components/ModalComponent";
import {getTokenVerify} from "@/pages/api/getTokenVerify";



function Index(props) {


    getTokenVerify();

    const {token} = useAuth();
    const router = useRouter();

    const [page, setPage] = useState(0);
    const [totalPages, setTotalPages] = useState(1);
    const [empresasAereas, setEmpresasAereas] = useState([]);
    const [idEmpresasAereas, setidEmpresasAereas] = useState([]);


    const [modalIsOpen, setModalIsOpen] = useState(false);

    const openModal = (idEmpresaAerea) => {
        setidEmpresasAereas(idEmpresaAerea)
        setModalIsOpen(true);
    };

    const closeModal = () => {
        setModalIsOpen(false);
        router.reload();
    };

    //Buscando a lista de Empresas Aereas
    useEffect(() => {
        http.get(`/empresasaereas?page=${page}&size=10`, {
            headers: {
                'Authorization': `Bearer ${token}`
            },
            params: {page}
        })
            .then(response=>{
                setEmpresasAereas(response.data.content);
                setTotalPages(response.data.totalPages);
            })
            .catch((error) => {
                console.error('Erro ao listar empresas', error);
            });
    }, [page, token]);

    const handleDeleteEmpresa = () =>{
        http.delete(`/empresasaereas/${idEmpresasAereas}`, {
            headers:{
                'Authorization':`Bearer ${token}`
            }
        })
            .then(()=>{
                closeModal();
            })
            .catch((erro)=>{
                console.error("Erro ao exlcuir ",erro );
            })
    }

    return (
        <>
            <Head>
                <title>Agencia de Viagems - Companhias Aereas </title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            <main className="container">
                <div className="container d-sm-flex flex-row justify-content-between mb-3">
                    <h3>Lista de Empresas</h3>
                    <Link href="/backoffice/companhia_aerea/cadastro" className="btn btn-success pe-5 ps-5" onClick={(e) => {
                    }}>Novo
                    </Link>
                </div>

                <table className="table">
                    <thead>
                    <tr className="border border-2 border-warning">
                        <th scope="col">Nome</th>
                        <th scope="col">Cnpj</th>
                        <th scope="col" className="d-flex justify-content-end">Ações</th>
                    </tr>
                    </thead>
                    <tbody>
                    {empresasAereas && empresasAereas.length > 0 ?(
                        empresasAereas.map(empresaAerea=>
                        <tr key={empresaAerea.id}>
                            <td>{empresaAerea.nome}</td>
                            <td>{empresaAerea.cnpj}</td>
                            <td className="d-flex justify-content-end">
                                <Link href={`/backoffice/companhia_aerea/${empresaAerea.id}`}
                                      className="btn btn-success me-3">Editar</Link>
                                <button className="btn btn-danger"
                                        onClick={() => openModal(empresaAerea.id)}>Excluir
                                </button>
                            </td>
                        </tr>
                        )
                    ):(
                        <tr>
                            <td colSpan="6">Nenhum aeroporto encontrado.</td>
                        </tr>
                    )}
                    </tbody>

                </table>

                <Paginacao page={page} totalPages={totalPages} setPage={setPage}/>

                <ModalComponent isOpen={modalIsOpen}>
                    <p>Deseja excluir o empresa? </p>
                    <div className="d-flex justify-content-between">

                        <button className="btn  bg-success me-2" onClick={(e) => {
                            e.preventDefault();
                            handleDeleteEmpresa()
                        }}>CONFIRMAR
                        </button>
                        <button className="btn  btn-danger" onClick={closeModal}>CONCELAR</button>
                    </div>

                </ModalComponent>


            </main>
        </>
    );
}

export default Index;